Controllers/PredictCropController.cs
using MainApp.Data;
using MainApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MainApp.Controllers
{
    public class PredictCropController : Controller
    {
        private readonly ApplicationDbContext _context;
        public PredictCropController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            UserViewModel userViewModel = new UserViewModel();

                //create SelectListItem
                userViewModel.UserList = _context.Users.
                                           Select(a => new SelectListItem
                                           {
                                               Text = a.Name, // name to show in html dropdown
                                               Value = a.Id.ToString() // value of html dropdown
                                           }).ToList();
            
            //pass Model to view
            return View(userViewModel);
        }
        [HttpPost]
        public IActionResult Index(UserViewModel userViewModel)
        {
            
            //create SelectListItem
            userViewModel.UserList = _context.Users.
                                       Select(a => new SelectListItem
                                       {
                                           Text = a.Name, // name to show in html dropdown
                                           Value = a.Id.ToString() // value of html dropdown
                                       }).ToList();

                                       
            //pass Model to view
            return View(userViewModel);
        }
        public IActionResult PredictCrop()
        {
            return View();
        }
        
    }
}

Controllers/SoilHealthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MainApp.Data;
using MainApp.Models;

namespace MainApp.Controllers
{
    public class SoilHealthController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SoilHealthController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SoilHealth
        public async Task<IActionResult> Index()
        {
              return View(await _context.SoilInfo.ToListAsync());
        }


        // GET: SoilHealth/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.SoilInfo == null)
            {
                return NotFound();
            }

            var soilHealthParameters = await _context.SoilInfo
                .FirstOrDefaultAsync(m => m.SoilId == id);
            if (soilHealthParameters == null)
            {
                return NotFound();
            }

            return View(soilHealthParameters);
        }

        // GET: SoilHealth/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SoilHealth/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SoilId,SoilName,pH,EC,OC,OM,N,P,K,Zn,Fe,Cu,Mn,CaCO3,SoilNature")] SoilHealthParameters soilHealthParameters)
        {
            if (ModelState.IsValid)
            {
                _context.Add(soilHealthParameters);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(soilHealthParameters);
        }

        // GET: SoilHealth/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.SoilInfo == null)
            {
                return NotFound();
            }

            var soilHealthParameters = await _context.SoilInfo.FindAsync(id);
            if (soilHealthParameters == null)
            {
                return NotFound();
            }
            return View(soilHealthParameters);
        }

        // POST: SoilHealth/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SoilId,SoilName,pH,EC,OC,OM,N,P,K,Zn,Fe,Cu,Mn,CaCO3,SoilNature")] SoilHealthParameters soilHealthParameters)
        {
            if (id != soilHealthParameters.SoilId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(soilHealthParameters);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SoilHealthParametersExists(soilHealthParameters.SoilId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(soilHealthParameters);
        }

        // GET: SoilHealth/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.SoilInfo == null)
            {
                return NotFound();
            }

            var soilHealthParameters = await _context.SoilInfo
                .FirstOrDefaultAsync(m => m.SoilId == id);
            if (soilHealthParameters == null)
            {
                return NotFound();
            }

            return View(soilHealthParameters);
        }

        // POST: SoilHealth/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.SoilInfo == null)
            {
                return Problem("Entity set 'ApplicationDbContext.SoilInfo'  is null.");
            }
            var soilHealthParameters = await _context.SoilInfo.FindAsync(id);
            if (soilHealthParameters != null)
            {
                _context.SoilInfo.Remove(soilHealthParameters);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SoilHealthParametersExists(int id)
        {
          return _context.SoilInfo.Any(e => e.SoilId == id);
        }

        // GET: SoilHealth/Details/5
        public PartialViewResult GetSoilInfo(string userid)
        {

            //UserProfile user = (UserProfile)_context.Users.FirstOrDefault(m => m.Id == Convert.ToInt32(userid));

            List<SoilHealthParameters> soilHealthParameters = _context.SoilInfo
                .Where(m => m.UserId == Convert.ToInt32(userid)).ToList();

            return PartialView("_SoilDataTablePartial", soilHealthParameters);
          //  return PartialView(soilHealthParameters);
        }
        public PartialViewResult GetCropsList(int ph)
        {

            //UserProfile user = (UserProfile)_context.Users.FirstOrDefault(m => m.Id == Convert.ToInt32(userid));

            List<Crop> crops = _context.Crops
                .Where(m => m.ReqSoilPh >= ph).ToList();

            return PartialView("_CropsPartial", crops);
            //  return PartialView(soilHealthParameters);
        }

    }
}

Views/SoilHealth/Create.cshtml
@model MainApp.Models.SoilHealthParameters

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SoilHealthParameters</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SoilName" class="control-label"></label>
                <input asp-for="SoilName" class="form-control" />
                <span asp-validation-for="SoilName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="pH" class="control-label"></label>
                <input asp-for="pH" class="form-control" />
                <span asp-validation-for="pH" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EC" class="control-label"></label>
                <input asp-for="EC" class="form-control" />
                <span asp-validation-for="EC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OC" class="control-label"></label>
                <input asp-for="OC" class="form-control" />
                <span asp-validation-for="OC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OM" class="control-label"></label>
                <input asp-for="OM" class="form-control" />
                <span asp-validation-for="OM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="N" class="control-label"></label>
                <input asp-for="N" class="form-control" />
                <span asp-validation-for="N" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="P" class="control-label"></label>
                <input asp-for="P" class="form-control" />
                <span asp-validation-for="P" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="K" class="control-label"></label>
                <input asp-for="K" class="form-control" />
                <span asp-validation-for="K" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zn" class="control-label"></label>
                <input asp-for="Zn" class="form-control" />
                <span asp-validation-for="Zn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fe" class="control-label"></label>
                <input asp-for="Fe" class="form-control" />
                <span asp-validation-for="Fe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cu" class="control-label"></label>
                <input asp-for="Cu" class="form-control" />
                <span asp-validation-for="Cu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mn" class="control-label"></label>
                <input asp-for="Mn" class="form-control" />
                <span asp-validation-for="Mn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CaCO3" class="control-label"></label>
                <input asp-for="CaCO3" class="form-control" />
                <span asp-validation-for="CaCO3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoilNature" class="control-label"></label>
                <input asp-for="SoilNature" class="form-control" />
                <span asp-validation-for="SoilNature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/SoilHealth/Delete.cshtml
@model MainApp.Models.SoilHealthParameters

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SoilHealthParameters</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoilName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoilName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.pH)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.pH)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EC)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EC)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OC)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OC)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.N)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.N)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.P)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.P)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.K)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.K)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fe)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CaCO3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CaCO3)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoilNature)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoilNature)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SoilId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/SoilHealth/Details.cshtml
@model MainApp.Models.SoilHealthParameters

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SoilHealthParameters</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoilName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoilName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.pH)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.pH)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EC)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EC)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OC)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OC)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.N)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.N)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.P)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.P)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.K)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.K)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fe)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CaCO3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CaCO3)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoilNature)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoilNature)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.SoilId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/SoilHealth/Edit.cshtml
@model MainApp.Models.SoilHealthParameters

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SoilHealthParameters</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SoilId" />
            <div class="form-group">
                <label asp-for="SoilName" class="control-label"></label>
                <input asp-for="SoilName" class="form-control" />
                <span asp-validation-for="SoilName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="pH" class="control-label"></label>
                <input asp-for="pH" class="form-control" />
                <span asp-validation-for="pH" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EC" class="control-label"></label>
                <input asp-for="EC" class="form-control" />
                <span asp-validation-for="EC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OC" class="control-label"></label>
                <input asp-for="OC" class="form-control" />
                <span asp-validation-for="OC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OM" class="control-label"></label>
                <input asp-for="OM" class="form-control" />
                <span asp-validation-for="OM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="N" class="control-label"></label>
                <input asp-for="N" class="form-control" />
                <span asp-validation-for="N" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="P" class="control-label"></label>
                <input asp-for="P" class="form-control" />
                <span asp-validation-for="P" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="K" class="control-label"></label>
                <input asp-for="K" class="form-control" />
                <span asp-validation-for="K" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zn" class="control-label"></label>
                <input asp-for="Zn" class="form-control" />
                <span asp-validation-for="Zn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fe" class="control-label"></label>
                <input asp-for="Fe" class="form-control" />
                <span asp-validation-for="Fe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cu" class="control-label"></label>
                <input asp-for="Cu" class="form-control" />
                <span asp-validation-for="Cu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mn" class="control-label"></label>
                <input asp-for="Mn" class="form-control" />
                <span asp-validation-for="Mn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CaCO3" class="control-label"></label>
                <input asp-for="CaCO3" class="form-control" />
                <span asp-validation-for="CaCO3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoilNature" class="control-label"></label>
                <input asp-for="SoilNature" class="form-control" />
                <span asp-validation-for="SoilNature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/SoilHealth/Index.cshtml
@model IEnumerable<MainApp.Models.SoilHealthParameters>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SoilName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.pH)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EC)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OC)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.N)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.P)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.K)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fe)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CaCO3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoilNature)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SoilName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.N)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.P)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.K)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CaCO3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoilNature)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.SoilId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.SoilId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.SoilId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/SoilHealth/_CropsPartial.cshtml
@model IEnumerable<MainApp.Models.Crop>


@{
    ViewData["Title"] = "CropDataTable";
}

<h1>Suitable Crops</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CropName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CropType)
            </th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CropName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CropType)
                </td>
               
            </tr>
        }
    </tbody>
</table>

Views/SoilHealth/_SoilDataTablePartial.cshtml
@model IEnumerable<MainApp.Models.SoilHealthParameters>


@{
    ViewData["Title"] = "SoilDataTable";
}

<h1>PredictCrop</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SoilName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.pH)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fe)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.K)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CaCO3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoilNature)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SoilName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.pH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cu)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fe)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.K)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CaCO3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoilNature)
                </td>
                <td>
                    @*@Html.ActionLink("Predict Crop", "PredictCrop", "PredictCrop", item.pH, new { @class = "myCustomLink" })*@
                   @* @Html.ActionLink("Predict Crop", "PredictCrop", "PredictCrop", item.pH, new { @class = "btn btn-primary" })*@
                    <button id="btn" type="button" class="btn btn-primary" value="Predict Crop">Predict Crop</button>
               </td>

            </tr>
        }
    </tbody>
</table>
<div id="MyPopup" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
 
            <div class="modal-body">
                
            </div>
            <div class="modal-footer">
                <input type="button" id="btnClosePopup" value="Close" class="btn btn-danger" data-dismiss="modal" />
            </div>
        </div>
    </div>
</div>

<script>
 
    $("#btn").click(function (e) {
        e.preventDefault();
        var $buttonClicked = $(this);
        var id = $buttonClicked.attr('data-id');
        var options = { "backdrop": "static", keyboard: true };
        $.ajax({
            url: "@Url.Action("GetCropsList","SoilHealth")",
            data: { ph: 1 },
            type: "Get",
            dataType: "html",
            success: function (data) {
                $('.modal-body').html(data);
                $('#MyPopup').modal(options);
                $('#MyPopup').modal('show');
            },
            error: function () {
                alert("Dynamic content load failed.");
            }
        });
        return false;
    });
    $("#btnClosePopup").click(function () {
        $("#MyPopup").modal("hide");
    });
</script>

<style type="text/css">
    .myCustomLink {
        color: green;
        font-weight: bold;
    }
    
</style> 